### ISSUE TITLE
docz.site not working in firefox windows

### ISSUE THREAD

**Issue by terebentina** [pedronauck/docz#724] opened 2019-03-26 17:54 UTC
## Bug Report

**Describe the bug**
https://www.docz.site/ doesn't load in Firefox 66 (possibly others too) on Windows 10

*A clear and concise description of what the bug is.*

**To Reproduce**

```shell
FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

This in devtools:
![image](https://user-images.githubusercontent.com/238611/55021223-0d4f4900-5001-11e9-9e08-bb72092bffad.png)

**Comment by arthurdenner** [comment] 2019-03-27 00:58
Duplicate of [pedronauck/docz-website#50](https://github.com/pedronauck/docz-website/issues/50).

**Comment by pedronauck** [comment] 2019-03-29 17:28
closed in favor of [this](pedronauck/docz-website#50)

**Closed by pedronauck** 2019-03-29 17:28 UTC
Labels: v1
