### ISSUE TITLE
How to include default theme sidebar into a custom theme ?

### ISSUE THREAD

**Issue by michelson** [pedronauck/docz#285] opened 2018-09-04 02:48 UTC
## Question
Hi @pedronauck . I've published my site with docz at [dante2 repo](https://michelson.github.io/dante2/#/) I'm using a very simple custom theme and I was wondering if it's possible to include some components of the default theme in my [implementation](https://github.com/michelson/dante2/tree/master/src/docs) ? like the sidebar ?
otherwise, which approach will you recommend ? copy entire theme on my src like [docz site](https://github.com/pedronauck/docz-website) ?

**Comment by zephraph** [comment] 2018-09-05 17:41
Likely a duplicate of #283.

**Comment by pedronauck** [comment] 2018-09-05 18:14
I'll close in favor of this is a duplicated issue!

**Comment by pedronauck** [comment] 2018-09-05 18:14
Please, check my response there's :)

**Closed by pedronauck** 2018-09-05 18:14 UTC
