### ISSUE TITLE
Uncaught TypeError: Cannot set property 'jsx' of undefined

### ISSUE THREAD

**Issue by bakso** [pedronauck/docz#339] opened 2018-09-19 08:22 UTC
## Bug Report

Today i run `npm install`, and `npm run doc`(alias of `docz dev`, docz was installed in the project dir), caght error below:

![image](https://user-images.githubusercontent.com/659130/45740433-d6e6da80-bc27-11e8-8b7e-5e0cfcb82758.png)

`acorn$$1.plugins` is undefined.

![image](https://user-images.githubusercontent.com/659130/45740459-e49c6000-bc27-11e8-8d19-8d489031ed62.png)

**Comment by pedronauck** [comment] 2018-09-28 14:19
Can you give a repo with minimal setup of your project to reproduce the bug?

**Comment by nnecec** [comment] 2018-10-09 02:42
I still have this problem. 

I have remove node_modules and yarn.lock, and try `yarn install` again. It works.

**Comment by torch2424** [comment] 2018-10-09 08:35
Also got this issue. Downgrading docz to v0.11.2 worked for me. The strange thing is, I actually just used docz on another repo at the latest version `0.12.5`, and it worked fine. I think maybe some dependency is missing somewhere in the latest versions?

**Comment by kikorb** [comment] 2018-10-11 10:42
I just had the same problem. I managed to configure Docz and use it fine but when I tried to configure jest to have my tests passing again I had to add:

"@babel/register": "^7.0.0",
"babel-core": "^7.0.0-bridge.0",
"regenerator-runtime": "^0.12.1",

to my package.json in order to have Jest working. That created this issue for docz. I assume the culprit is having babel-core in addition to @babel/core.

**Comment by kikorb** [comment] 2018-10-11 11:00
Ok the issue seems to be in @babel/register somehow, I have removed the other 2 libraries and the error persist if the only change I do is add @babel/register to the project.

**Comment by kikorb** [comment] 2018-10-11 11:13
Ok I solved the issue adding "acorn": "5.7.3", to my dev dependencies. @babel/register updated some dependencies and acorn was not a fixed dependency.

**Comment by JoshRosenstein** [comment] 2018-10-12 18:56
Same here. i had latest version of acorn in my dev deps for my library, but had to downgrade it to get docz to work.

**Comment by JeSuis** [comment] 2019-03-26 15:47
FYI I had this problem and adding acorn alone to dev dependancies nor any other of the other suggestions would fix it
I saw styleguidest was using `buble` which has an old version as a dev dependency. 

I installed `^0.19.7` directly and was back in business.

**Comment by Glazy** [comment] 2019-04-28 12:14
Closing this issue since it hasn't had any activity in quite a few months. If you're still experiencing problems then please open up a fresh issue :+1:

**Closed by Glazy** 2019-04-28 12:14 UTC
Labels: question
