### ISSUE TITLE
Expecting Unicode escape sequence \uXXXX

### ISSUE THREAD

**Issue by Malarne** [pedronauck/docz#85] opened 2018-06-24 15:44 UTC
Hi, i tried to write some simple docs, and for detailing my variables, i can't use PropsTable (it's for Discord Bot, dunno if i can import Python classes, anyway) so i tried to write a simple <table> with html.
here is the code: https://github.com/Malarne/Docs/blob/master/index.mdx
(don't mind french, not important)
all the bottom badges works fine, but the <table> object return `11:16:08 AM: SyntaxError: /opt/build/repo/index.mdx: Expecting Unicode escape sequence \uXXXX (12:20)
11:16:08 AM:   10 | <tr>
11:16:08 AM:   11 | <th> ** Attribut: ** </th>
11:16:08 AM: > 12 | <th> ** \< channel \> ** </th>
11:16:08 AM:      |                     ^
11:16:08 AM:   13 | <th> ** \< role \> ** </th>
11:16:08 AM:   14 | <th> ** \< id \> ** </th>
11:16:08 AM:   15 | </tr>
11:16:08 AM: error Command failed with exit code 1.
11:16:08 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
Did i forgot any \ somewhere ? I hope i can make that work ...

**Comment by nicholasess** [comment] 2018-07-03 17:04
@Malarne I could not reproduce the problem with your project

**Comment by nicholasess** [comment] 2018-07-06 14:22
@pedronauck can you close the issue?

**Comment by pedronauck** [comment] 2018-07-06 14:58
If @Malarne answer us, we open this issue again ✌️

**Closed** 2018-07-06 14:58 UTC
