### ISSUE TITLE
It doesnt start

### ISSUE THREAD

**Issue by maxguzenski** [pedronauck/docz#5] opened 2018-06-12 02:35 UTC
Hi, can you help me? Docz doesn't start...

```
 ERROR  Failed to compile with 1 errors23:29:58

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:304:26)
    at /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:267:7

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Comment by pedronauck** [comment] 2018-06-12 02:44
which version of node you're using @maxguzenski?

**Comment by sos418** [comment] 2018-06-12 02:48
I can't also start. But my error msg is different

` ERROR  Failed to compile with 1 errors                                 10:45:44

This relative module was not found:

* ../dd.mdx in ./.docz/app/imports.js`

node version:8.11.2
yarn version:1.7.0

**Comment by pedronauck** [comment] 2018-06-12 02:57
try to update for node v9 guys, I think that some packages aren't supporting old versions 😢

**Comment by pedronauck** [comment] 2018-06-12 02:58
here using node v8.0.0 I got this message:

```
error @webpack-contrib/config-loader@1.1.2: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
```

**Comment by renatorib** [comment] 2018-06-12 03:12
@sos418 try puting your `.mdx` file into a `src` folder. I think it's a bug.

**Comment by renatorib** [comment] 2018-06-12 03:15
@sos418 nope, I am wrong. It's not a bug.
Docz will find for `src` by default, but you can change/configure it in your `doczrc.js`

https://www.docz.site/documentation/project-configuration#basic-config

**Comment by sos418** [comment] 2018-06-12 03:50
I try to update node version to 9.11.1 and put my `mdx` file into a `src` folder.

Still have error msg:
` ERROR  Failed to compile with 1 errors                                    11:46:59

This relative module was not found:

* ./ in ./src/dd.mdx`

**Comment by sos418** [comment] 2018-06-12 03:50
``

**Comment by pedronauck** [comment] 2018-06-12 03:59
I just release now @sos418 by fixing that, just try it please 🙏

**Comment by liorbentov** [comment] 2018-06-12 07:32
@pedronauck, still getting the error:
![image](https://user-images.githubusercontent.com/8587019/41276127-dd2b7e18-6e2b-11e8-8f98-c915a8461ae5.png)
```
* app/components/bzm-button/bzm-button.mdx in ./.docz/app/imports.js
```

**Comment by joshuaalpuerto** [comment] 2018-06-12 08:15
@pedronauck running `docz dev`  is not working and throws nothing. 

<img width="919" alt="screen shot 2018-06-12 at 4 12 46 pm" src="https://user-images.githubusercontent.com/7126484/41278134-a81d0b44-6e5b-11e8-8d48-cf29d79b073b.png">

Tried adding `doczrz.js` to root but still nothing.

Cheers!

**Comment by maxguzenski** [comment] 2018-06-12 11:44
tested with node 10.4.0 and 9.2.0

```
yarn docz
yarn run v1.6.0
(node:25766) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning package.json: No license field
$ docz dev
ℹ  info      Removing old app files
ℹ  info      Creating new docz files
ℹ  info      Setup entries socket on port 8089


 ERROR  Failed to compile with 1 errors                                                                                     08:41:37

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:304:26)
    at /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:267:7

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx



 WAIT  Compiling...                                                                                                         08:41:37



 ERROR  Failed to compile with 1 errors                                                                                     08:41:38

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:138:11)
    at items.map (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:69:29)
    at createPresetDescriptors (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:61:10)
    at passPerPreset (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:53:96)
    at cachedFunction (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/caching.js:32:19)
    at presets.presets (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-descriptors.js:25:84)
    at mergeChainOpts (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:304:26)
    at /Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:267:7
    at buildRootChain (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/config-chain.js:64:29)
    at loadPrivatePartialConfig (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/partial.js:55:55)
    at Object.loadPartialConfig (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/@babel/core/lib/config/partial.js:80:18)
    at Object.<anonymous> (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/babel-loader/lib/index.js:82:26)
    at Generator.next (<anonymous>)
    at step (/Users/max/Projetos/mytestapp/apps/d4_web/assets/node_modules/docz-core/node_modules/babel-loader/lib/index.js:3:221)

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

my package.json 
```
{
  "name": "myapptest",
  "version": "1.1.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@fortawesome/fontawesome": "^1.0.1",
    "@fortawesome/fontawesome-free-brands": "^5.0.0",
    "@fortawesome/fontawesome-pro-light": "^5.0.0",
    "@fortawesome/fontawesome-pro-regular": "^5.0.0",
    "@fortawesome/fontawesome-pro-solid": "^5.0.0",
    "@fortawesome/react-fontawesome": "^0.0.20",
    "@reach/router": "^1.0.2",
    "babel-polyfill": "^6.26.0",
    "classnames": "^2.1.3",
    "dayjs": "^1.6.4",
    "google-maps": "^3.2.1",
    "hoist-non-react-statics": "^2.1.0",
    "mobx": "^4.0.0",
    "mobx-react": "^5.0.0",
    "mobx-state-tree": "^2.0.0",
    "normalize.css": "^8.0.0",
    "phoenix": "^1.2.0",
    "prop-types": "^15.5.4",
    "raven-js": "^3.1.1",
    "react": "^16.4.0",
    "react-autosize-textarea": "^0.4.9",
    "react-content-loader": "^3.0.0",
    "react-dom": "^16.4.0",
    "react-intl": "^2.0.0-pr-3",
    "react-loadable": "^5.3.1",
    "react-overlays": "^0.8.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.0",
    "react-transition-group": "^2.2.0",
    "react-truncate": "^2.3.0",
    "react-waypoint": "^8.0.0",
    "styled-components": "^3.0.0",
    "uuid": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.0.0",
    "babel-loader": "^7.0.0",
    "babel-plugin-styled-components": "^1.3.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "copy-webpack-plugin": "^4.0.0",
    "css-loader": "*",
    "docz": "^0.2",
    "duplicate-package-checker-webpack-plugin": "^3.0.0",
    "eslint": "^4.2.0",
    "eslint-plugin-react": "^7.3.0",
    "exports-loader": "^0.7.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "favicons-webpack-plugin": "^0.0.9",
    "file-loader": "^1.0.0",
    "imports-loader": "^0.8.0",
    "postcss": "^6.0.0",
    "postcss-browser-reporter": "^0.5.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-each": "^0.10.0",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.5",
    "postcss-nested": "^3.0.0",
    "prepack-webpack-plugin": "^1.1.0",
    "react-addons-perf": "^15.0.0",
    "react-perf-devtool": "^3.0.2",
    "style-loader": "^0.21.0",
    "svgo-loader": "^2.0.0",
    "uglify-loader": "^2.0.0",
    "url-loader": "^1.0.0",
    "webcolors": "^1.2.2",
    "webpack": "^4.4.1",
    "webpack-bundle-analyzer": "^2.3.1",
    "webpack-bundle-size-analyzer": "^2.6.0",
    "webpack-cli": "^2.0.13",
    "webpack-error-notification": "^0.1.6"
  },
  "scripts": {
    "start": "webpack --config webpack.config.babel.js --watch-stdin --color --env.desktop",
    "stats": "webpack --config webpack.config.babel.js --env.desktop --json > stats.json",
    "docz": "docz dev"
  }
}
```

**Comment by Swapnull** [comment] 2018-06-12 11:50
It looks like this is an issue with using babel6 rather than babel7. 

I am getting the same `Plugin/Preset files are not allowed to export objects, only functions` as @maxguzenski when using `babel-preset-env` and `babel-preset-react`.
When I upgraded to `@babel/preset-env` and `@babel/preset-react` (The babel7 implementation) it worked fine. 

Unfortunately tools like parcelJs don't support babel7 yet as its still in beta. I don't want to have to do a full webpack implementation just for a documentation tool. 

@pedronauck can you confirm if this will work with babel6 and provide an example config that works?

**Comment by maxguzenski** [comment] 2018-06-12 12:01
I don't not if babel 7 is ready for production... but docz should support babel 6...

**Comment by itaditya** [comment] 2018-06-12 13:27
@pedronauck I am having the issue mentioned in issue descrption.

```
 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
```

System Details - 
Node v9.3.0
Windows 7 32-bit

My project is [here](https://github.com/itaditya/react-docz-trial)

**Comment by Swapnull** [comment] 2018-06-12 15:55
@thomhos - I guess you are using `babel-preset-react` and `babel-preset-typescript` ? 
The react preset comes with flow included, which causes this error.
It has been fixed in Babel 7, but they have no plans on putting it in babel 6. (https://github.com/babel/babel/pull/6118)

As for the rendering undefined. Do you have the mdx file?

**Comment by pedronauck** [comment] 2018-06-13 02:52
Great work helping here @Swapnull... Docz is entirely built around babel 7 integrations, so if you use some babel older package, probably you will get an error. Try to update your babel packages and give some feedback for us about that!

**Comment by pedronauck** [comment] 2018-06-13 02:52
I think that is a good thing put this information someplace on-site or GitHub

**Comment by Ronnyrr** [comment] 2018-06-13 09:01
Can't seem to get it working either. Same `Plugin/Preset files are not allowed to export objects, only functions.` error. Using it in this way. Babel version: `"babel-core": "^6.26.0"`, since 7 isn't stable. But if I read this correct I have to use babel 7?

![screen shot 2018-06-13 at 10 59 48](https://user-images.githubusercontent.com/4519142/41341029-fe0b905a-6ef8-11e8-96bc-51f4b68b8eb4.png)

**Comment by itaditya** [comment] 2018-06-13 09:09
I have tried this using babel7 also

**Comment by pedronauck** [comment] 2018-06-13 22:59
Exactly @Ronnyrr, docz just works with babel 7, so you need to use it instead of babel 6 by now. I thinking of a solution for that, like a `babel6`property on project configuration... what do you think about that?

**Comment by fzaninotto** [comment] 2018-06-14 20:40
My project also uses Babel 6 and I have the same error. Please make it babel6 compatible!

**Comment by pedronauck** [comment] 2018-06-17 02:00
Babel 6 support now is possible by using `docz-plugin-babel6` release in [v0.2.6](https://github.com/pedronauck/docz/releases/tag/v0.2.6)

**Closed by pedronauck** 2018-06-17 02:00 UTC
Labels: bug, enhancement

**Comment by ThaddeusJiang** [comment] 2018-08-17 00:37
sorry, my project can't work with babel6.

**Comment by Swapnull** [comment] 2018-08-17 06:17
@ThaddeusJiang Open a new issue with some information such as error messages, screenshots and an example repo and somebody will have a look.
