### ISSUE TITLE
PropsTable fails when using an imported array for PropTypes.oneOf()

### ISSUE THREAD

**Issue by hnordt** [pedronauck/docz#315] opened 2018-09-09 13:27 UTC
PropTable fails when using an imported array for `PropTypes.oneOf()`:

![Bug](https://d.pr/i/Ezuxxj+)

**Comment by karlossg** [comment] 2018-09-10 21:33
Hi, i found what the problem is, in humanize-prop.ts there is map on enum type with dont have map method, i have proposal how to repair it, should i do PR?

**Comment by pedronauck** [comment] 2018-09-11 04:16
Fixed, will be released in the next version!

**Closed by pedronauck** 2018-09-11 04:16 UTC
Labels: bug

**Comment by pedronauck** [comment] 2018-09-12 18:52
For sure @hnordt, this is something related to react-docgen, we figure out a better way to handle docgen to resolve a lot of fixes around it 😕

**Comment by hnordt** [comment] 2018-09-12 20:30
@pedronauck do the project has an issue for tracking it? I couldn't find it, sorry.
