### ISSUE TITLE
TypeError: n is not a function

### ISSUE THREAD

**Issue by clock157** [pedronauck/docz#551] opened 2018-12-24 05:39 UTC
## Bug Report
docz: 0.12.17 & 0.13.5

**To Reproduce**
npx docz dev

```shell
/Users/puwei/Dev/test/test_lib/test-library/node_modules/_docz-core@0.12.16@docz-core/dist/index.js:5227
        n({
        ^

TypeError: n is not a function
    at parseHtml (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_docz-core@0.12.16@docz-core/dist/index.js:5227:9)
    at template (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_docz-core@0.12.16@docz-core/dist/index.js:5365:21)
    at MiniHtmlWebpackPlugin.plugin (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_mini-html-webpack-plugin@0.2.3@mini-html-webpack-plugin/index.js:17:33)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_webpack@4.28.2@webpack/lib/Compiler.js:363:19)
    at onCompiled (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_webpack@4.28.2@webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_webpack@4.28.2@webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_webpack@4.28.2@webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_webpack@4.28.2@webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/puwei/Dev/test/test_lib/test-library/node_modules/_tapable@1.1.1@tapable/lib/Hook.js:154:20)
```

I flowed the minified code, found that `e` is string 'null', not null.
```
getHtmlFilepath = e =>
    e ? path.resolve(root$1, e) : fromTemplates("index.tpl.html"),
htmlTemplate = async e =>
    compiled(getHtmlFilepath(e), { minimize: !1, escape: !1 }),
```
so it complied an error: 
```
 { Error: ENOENT: no such file or directory, open '/Users/puwei/Dev/test/test_lib/test-library/null'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/puwei/Dev/test/test_lib/test-library/null' }
```

**Comment by clock157** [comment] 2018-12-24 06:13
bad:
![image](https://user-images.githubusercontent.com/4002237/50392065-de1d0780-0785-11e9-9300-af50344ffd5c.png)
good: an old repo;
![image](https://user-images.githubusercontent.com/4002237/50392085-0278e400-0786-11e9-99e3-10fd5a5851b3.png)

**Comment by Godsenal** [comment] 2018-12-24 06:57
I have a same issue. As @clock157 said, html path is set to string `'null'` when `indexHtml` option is set to default.

**Comment by aleen42** [comment] 2018-12-24 08:35
Same issue, and how to fix it?

**Comment by Godsenal** [comment] 2018-12-24 08:45
@aleen42 right now, set default value  manually in `doczrc.js` works for me.

**Comment by aleen42** [comment] 2018-12-24 08:47
Meet another problem when setting with `null` manually, and what value should I set?

```
Module not found: Can't resolve 'null' in 'xxx/.docz/app'
```

**Comment by aleen42** [comment] 2018-12-24 08:47
Meet another problem when setting with `null` manually, and what value should I set?

```
Module not found: Can't resolve 'null' in 'xxx/.docz/app'
```

**Comment by clock157** [comment] 2018-12-24 08:49
try set empty string '' ?  @aleen42

**Comment by Godsenal** [comment] 2018-12-24 08:51
`undefined` works for me.

**Comment by aleen42** [comment] 2018-12-24 09:47
It seems not, just wait for the offical workarounds.

**Comment by Emiliano-Bucci** [comment] 2018-12-24 10:10
setting indexHtml to `undefined` works, but it leads (at least to me) to another error: Module not found: Can't resolve 'docz-theme-default' in...

**Comment by jedrichards** [comment] 2018-12-24 10:59
I've just tried downgrading Docz to older versions, and getting the error all the way back to 0.12.5 when I gave up. Is the error to do with some child dep of Docz perhaps?

**Comment by aleen42** [comment] 2018-12-24 11:09
@jedrichards Apparently due to sub-depedencies as there were no any recent commits today, when the problem arose.

**Comment by jedrichards** [comment] 2018-12-24 16:12
@aleen42 I think so too. Incidentally my Gatsby build has also broken if I `rm -rf node_modules && rm yarn.lock && yarn install`, so I think there's a bad sub-dep somewhere.

**Comment by chpwssn** [comment] 2018-12-24 16:17
@jedrichards if you had the `yarn.lock` in version control before your `rm -rf node_modules && rm yarn.lock && yarn install` would diffing the previous version against your current `yarn.lock` reveal some potential candidates for what has changed?

**Comment by JustFly1984** [comment] 2018-12-25 06:40
I'm confirming an issue, but I've updated from 0.12.15 to 0.13.5 with npm accidentally. and now reverting it back doesn't help. cleaning `node_modules`, package-lock.json`and `yarn-lock.json` does not help.

**Comment by matextrem** [comment] 2018-12-26 13:42
Any solution?

**Comment by pedronauck** [comment] 2018-12-26 13:48
I'm trying to fix that, I guess that the latest release of `env-dot-prop` doesn't parse the default value, so booleans and null values aren't parsing 😕I trying to reproduce the bug locally to fix.

**Comment by pedronauck** [comment] 2018-12-26 18:09
Hmm, I think that the problem here is that we don't have tests to prevent this type of bug and sometimes this bugs just happen in a clean install out of the monorepo. Because I always making manual tests using the examples in our monorepo and, for example, this bug didn't happen inside it. I don't know, but I think that this is the cost of don't have tests and always try to keep dependencies evergreen 😕 I'm making some stuff to try to avoid that, like release alpha and canary before the official release, start to write tests (unitary and e2e) and keep some pieces out of our core (like use poi as a bundler)...

**Comment by pedronauck** [comment] 2018-12-26 19:35
I was suspicious of it @simonepri, I tried to find any changelog with the breaking changes, but I didn't find. Btw, I change the default value of `get` to use conditional. I'm testing some canary release now and soon as possible releasing the patch, thanks to the tip 🙏

**Comment by simonepri** [comment] 2018-12-26 19:39
@pedronauck changes can be found [here](https://github.com/simonepri/env-dot-prop/pull/4#issuecomment-449733381)

**Comment by pedronauck** [comment] 2018-12-26 19:44
Now docz-core is updated with the latest version, thanks @simonepri 🙏The bug is fixed, I'm releasing some new version fixing this bug :)

**Comment by mohsinulhaq** [comment] 2018-12-26 19:44
thanks!

**Comment by pedronauck** [comment] 2018-12-26 19:50
Fixed on [v0.13.6](https://github.com/pedronauck/docz/releases/tag/v0.13.6) ✅

**Closed by pedronauck** 2018-12-26 19:50 UTC

**Comment by simonepri** [comment] 2018-12-26 19:56
@pedronauck I've unpublished `env-dot-prop@1.1.1` and released `env-dot-prop@1.1.2`

**Comment by simonepri** [comment] 2018-12-26 20:07
@pedronauck I think that [this](https://github.com/pedronauck/docz/commit/5644343) should be reverted and not needed anymore.

Actually I think you possibly introduced some other bug.
![image](https://user-images.githubusercontent.com/3505087/50456043-00638080-0952-11e9-9ca4-7f2ab33e05c7.png)
This always gets true even if getEnv returns false.

**Comment by pedronauck** [comment] 2018-12-26 20:07
Awesome @simonepri, thanks to the help, btw your package is really useful, I love it ❤️

**Comment by pedronauck** [comment] 2018-12-26 20:08
Mother of good, really, u'right 😕

**Comment by simonepri** [comment] 2018-12-26 20:10
Can you please if `env-dot-prop@1.1.2` fix the problem as well?
Thanks!

**Comment by pedronauck** [comment] 2018-12-26 20:11
I updated to version `2.0.1`, is fixing on that version too, right @simonepri ?

**Comment by simonepri** [comment] 2018-12-26 20:12
Yes that version is stable and tested.

**Comment by pedronauck** [comment] 2018-12-26 20:13
right, I'm reverting and releasing now 🙏
