### ISSUE TITLE
Polymer/Web components - possibly babel issue

### ISSUE THREAD

**Issue by eavichay** [pedronauck/docz#22] opened 2018-06-13 07:36 UTC
## Bug Report

I am trying to create docz for a library of custom elements, most of the are built on top of Polymer.
as React supports working with web-components, the babel transpiling is not configured to support that.

**To Reproduce**

Add custom element component, preferably Polymer based (not mandatory)

1. Go to 'localhost://3000'
2. Open dev-tools console
3. Error: `Uncaught TypeError: Class constructor PolymerElement cannot be invoked without 'new'`

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**
Web component to work ;)

## Enviroment
Windows 10 :(
Node 9.x
npm 5+

## Docz mdx file

```mdx
---
name: card-layout
---

import { Playground } from 'docz';
import CardLayout from './components/card-layout.js';

# CardLayout

## Basic usage

<Playground>
  <card-layout>
    <div slot="header">Header</div>
  </card-layout>
</Playground>
```

**Comment by pedronauck** [comment] 2018-06-13 22:49
I think that this is not a bug in fact, but an enhancement. Create something like `docz-plugin-webcomponents-  will be nice here!

**Comment by eavichay** [comment] 2018-06-15 06:15
Using web-components you are mostly targeting latest browsers (supports class syntax). This means that actually babel is not required except for object-spread, possibly decorators. But for some reason it just doesn't work, even when I provide a custom .babelrc file. Is there any way to reach out to the webpack configuration?

**Comment by pedronauck** [comment] 2018-06-27 01:50
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/integration-with-polymer)

**Closed by pedronauck** 2018-06-27 01:50 UTC
Labels: enhancement

**Comment by gusgzk** [comment] 2019-03-20 16:40
The problem exists due to babel transpiles the classes back to ES5 functions and the Web Components specification says the registered components via `customElements.define` must be ES6 classes.

I don't know how Docz internally works, but maybe could be possible bypassing babel importing a .mjs file.
